let ok = 1;
let q = __chr(34);
let s = "{";
let s = s + q;
let s = s + "x";
let s = s + q;
let s = s + ":42}";
let d = json_parse(s);
if json_get(d, "x") != 42 { let ok = 0; emit "FAIL x"; };
let s2 = "{";
let s2 = s2 + q;
let s2 = s2 + "name";
let s2 = s2 + q;
let s2 = s2 + ":";
let s2 = s2 + q;
let s2 = s2 + "olang";
let s2 = s2 + q;
let s2 = s2 + ",";
let s2 = s2 + q;
let s2 = s2 + "ver";
let s2 = s2 + q;
let s2 = s2 + ":2}";
let d2 = json_parse(s2);
if json_get(d2, "name") != "olang" { let ok = 0; emit "FAIL name"; };
if json_get(d2, "ver") != 2 { let ok = 0; emit "FAIL ver"; };
let arr = json_parse("[10,20,30]");
if __array_get(arr, 1) != 20 { let ok = 0; emit "FAIL arr"; };
if ok { emit "PASS"; } else { emit "FAIL"; };
