let _tv_ok = 1;
let _tv_f = 0;
fn _tv_chk(_tc_n, _tc_g, _tc_e) { if _tc_g != _tc_e { let _tv_ok = 0; let _tv_f = _tv_f + 1; emit "FAIL " + _tc_n + " got=" + __to_string(_tc_g); }; };
_tv_chk("add", 3 + 4, 7);
_tv_chk("sub", 10 - 3, 7);
_tv_chk("mul", 6 * 7, 42);
_tv_chk("div", 15 / 3, 5);
_tv_chk("mod", 17 % 5, 2);
_tv_chk("floor", __floor(3.7), 3);
_tv_chk("ceil", __ceil(3.2), 4);
_tv_chk("isqrt", __isqrt(25), 5);
_tv_chk("eq1", __eq(5, 5), 1);
_tv_chk("eq0", __eq(5, 6), 0);
_tv_chk("lt", 3 < 5, 1);
_tv_chk("gt", 5 > 3, 1);
_tv_chk("le", 3 <= 3, 1);
_tv_chk("ge", 5 >= 5, 1);
_tv_chk("len_s", len("hello"), 5);
_tv_chk("char_at", char_at("abc", 1), "b");
_tv_chk("substr", substr("hello world", 0, 5), "hello");
_tv_chk("to_num", __to_number("42"), 42);
_tv_chk("to_str", __to_string(42), "42");
let _tv_a = [10, 20, 30];
_tv_chk("len_a", len(_tv_a), 3);
_tv_chk("a0", _tv_a[0], 10);
_tv_chk("a2", _tv_a[2], 30);
let _tv_d = { name: "test", val: 42 };
_tv_chk("d_name", _tv_d.name, "test");
_tv_chk("d_val", _tv_d.val, 42);
_tv_chk("bitor", __bit_or(0, 1), 1);
_tv_chk("bitand", __bit_and(15, 9), 9);
_tv_chk("bitxor", __bit_xor(15, 9), 6);
let _tv_h = __sha256("hello");
_tv_chk("sha256", substr(_tv_h, 0, 8), "2cf24dba");
let _tv_h5 = __sha512("hello");
_tv_chk("sha512", substr(_tv_h5, 0, 8), "9b71d224");
let _tv_k = "0123456789abcdef0123456789abcdef";
_tv_chk("aes", __aes_decrypt(_tv_k, __aes_encrypt(_tv_k, "hello world 1234")), "hello world 1234");
_tv_chk("type_n", __type_of(42), "number");
_tv_chk("type_s", __type_of("hi"), "string");
_tv_chk("type_a", __type_of([1]), "array");
_tv_chk("time", __time() > 0, 1);
_tv_chk("not0", __logic_not(0), 1);
_tv_chk("not1", __logic_not(1), 0);
_tv_chk("mol_s", __mol_s(13920), 3);
_tv_chk("mol_r", __mol_r(13920), 6);
_tv_chk("mol_v", __mol_v(13920), 3);
_tv_chk("mol_p", __mol_pack(3, 6, 3, 0, 0), 13920);
let _tv_m1 = map([1,2,3], fn(x) { return x * 2; });
_tv_chk("map", len(_tv_m1), 3);
_tv_chk("map_v", _tv_m1[0], 2);
let _tv_f1 = filter([1,2,3,4,5], fn(x) { return x > 3; });
_tv_chk("filter", len(_tv_f1), 2);
_tv_chk("reduce", reduce([1,2,3,4,5], fn(a,b) { return a+b; }), 15);
let _tv_s1 = sort([3,1,2]);
_tv_chk("sort", _tv_s1[0], 1);
let _tv_c1 = contains("hello world", "world");
_tv_chk("contains", _tv_c1, 1);
let _tv_sp = split("a,b,c", ",");
_tv_chk("split", len(_tv_sp), 3);
_tv_chk("join", join(["x","y"], "-"), "x-y");
let _tv_p1 = pipe(5, fn(x) { return x+1; }, fn(x) { return x*2; });
_tv_chk("pipe", _tv_p1, 12);
_tv_chk("ok", unwrap(ok(42)), 42);
_tv_chk("err", unwrap_or(err("x"), 0), 0);
_tv_chk("type_name", type_name(42), "Num");
let _tv_dd = { x: 7 };
_tv_chk("interp", $"x={_tv_dd.x}", "x=7");
let _tv_comp = [x * 2 for x in [1,2,3]];
_tv_chk("comp", _tv_comp[0], 2);
_tv_chk("file", len(__file_read("data/test_small.txt")) > 0, 1);
_tv_chk("readdir", len(__readdir("stdlib")) > 0, 1);
if _tv_ok { emit "PASS"; } else { emit "FAIL " + __to_string(_tv_f); };
