fn make_adder(x) { return fn(y) { return x + y; }; };
let add5 = make_adder(5);
let add10 = make_adder(10);
fn mul(x) { return fn(y) { return x * y; }; };
let double = mul(2);
let triple = mul(3);
fn compose(f, g) { return fn(x) { return f(g(x)); }; };
let inc_double = compose(fn(x) { return x + 1; }, fn(x) { return x * 2; });
fn greet(prefix) { return fn(name) { return prefix + " " + name; }; };
let hello = greet("Hello");
let _pass = 0;
let _fail = 0;
fn check(name, got, want) { if got == want { _pass = _pass + 1; } else { emit "FAIL: " + name + " got=" + __to_string(got) + " want=" + __to_string(want); _fail = _fail + 1; }; };
check("add5(10)", add5(10), 15);
check("add5(3)", add5(3), 8);
check("add10(7)", add10(7), 17);
check("double(6)", double(6), 12);
check("triple(4)", triple(4), 12);
check("compose", inc_double(5), 11);
check("greet", hello("Nox"), "Hello Nox");
check("independent", add5(1) + add10(1), 16);
fn apply(f, x) { return f(x); };
check("apply_closure", apply(add5, 100), 105);
fn make_pair(a, b) { return fn(sel) { if sel == 0 { return a; } else { return b; }; }; };
let p = make_pair(42, 99);
check("pair_fst", p(0), 42);
check("pair_snd", p(1), 99);
emit __to_string(_pass) + "/" + __to_string(_pass + _fail) + " closure tests passed";
